version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python Bot.py
    environment:
      - PYTHONUNBUFFERED=1
